"""Builds src/Banccoon.App/Resources/Fonts/Heroicons-Outline.ttf and Controls/Heroicons.cs.

Heroicons ship as SVGs only, and the outline set is drawn with 1.5px round-capped *strokes*,
which a font can't hold (glyphs are filled outlines). So for every icon in icons.txt this:
  1. converts its strokes to filled outlines (picosvg, the same stroke-to-fill Google's
     nanoemoji font tooling uses),
  2. merges the overlapping pieces into one clean outline (skia-pathops union),
  3. writes it as a TrueType glyph at a Private Use Area codepoint (fontTools),
and then regenerates Controls/Heroicons.cs, the C# constants XAML uses for those codepoints.

Needs Python 3 with:  pip install picosvg fonttools   (picosvg pulls in skia-pathops)
Run from anywhere:    python tools/icon-font/build_heroicons_font.py
Inputs are committed (heroicons-2.2.0-outline-24/, MIT, see its LICENSE), so no network needed.
"""

from pathlib import Path

import pathops
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib.path import parse_path
from picosvg.svg import SVG

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SVG_DIR = HERE / "heroicons-2.2.0-outline-24"
FONT_OUT = ROOT / "src/Banccoon.App/Resources/Fonts/Heroicons-Outline.ttf"
CS_OUT = ROOT / "src/Banccoon.App/Controls/Heroicons.cs"

FAMILY = "Heroicons Outline"
UPM = 1000
ASCENT = 850   # the 24x24 icon fills the whole em box, centred on the text line like
DESCENT = 150  # other icon fonts, so FontImageSource draws it centred in its square
FIRST_CODEPOINT = 0xE000
SCALE = UPM / 24


def read_icon_names():
    lines = (HERE / "icons.txt").read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def build_glyph(name):
    svg = SVG.parse(str(SVG_DIR / f"{name}.svg")).topicosvg()
    # SVG is y-down from the top-left; fonts are y-up from the baseline.
    flip = (SCALE, 0, 0, -SCALE, 0, ASCENT)
    pieces = []
    for shape in svg.shapes():
        piece = pathops.Path()
        parse_path(shape.d, TransformPen(piece.getPen(), flip))
        pieces.append(piece)

    merged = pathops.Path()
    # TrueType wants outer contours clockwise; union also removes the stroke pieces' overlaps.
    pathops.union(pieces, merged.getPen(), clockwise=True)

    pen = TTGlyphPen(None)
    merged.draw(Cu2QuPen(pen, max_err=1.0, reverse_direction=False))
    return pen.glyph()


def to_pascal(name):
    return "".join(part.capitalize() for part in name.replace("-", " ").split())


def main():
    names = read_icon_names()
    glyph_order = [".notdef"] + names
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    cmap = {}
    for index, name in enumerate(names):
        glyphs[name] = build_glyph(name)
        cmap[FIRST_CODEPOINT + index] = name

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    glyf = fb.font["glyf"]
    metrics = {}
    for name in glyph_order:
        glyf[name].recalcBounds(glyf)
        metrics[name] = (UPM, getattr(glyf[name], "xMin", 0))
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=ASCENT, descent=-DESCENT)
    fb.setupNameTable({
        "familyName": FAMILY,
        "styleName": "Regular",
        "uniqueFontIdentifier": f"{FAMILY} Regular; Heroicons 2.2.0",
        "fullName": f"{FAMILY} Regular",
        "psName": "HeroiconsOutline-Regular",
        "version": "Version 2.2.0",
        "copyright": "Heroicons (c) Tailwind Labs, Inc., MIT License",
        "licenseDescription": "MIT License - see tools/icon-font/heroicons-2.2.0-outline-24/LICENSE",
    })
    fb.setupOS2(
        sTypoAscender=ASCENT, sTypoDescender=-DESCENT, sTypoLineGap=0,
        usWinAscent=ASCENT, usWinDescent=DESCENT,
        achVendID="NONE")
    fb.setupPost()
    fb.setupMaxp()
    FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
    fb.save(str(FONT_OUT))

    constants = "\n".join(
        f'    public const string {to_pascal(name)} = "\\u{FIRST_CODEPOINT + index:04X}";'
        for index, name in enumerate(names))
    CS_OUT.write_text(
        "// <auto-generated>\n"
        "// Generated by tools/icon-font/build_heroicons_font.py from tools/icon-font/icons.txt - edit\n"
        "// those and rerun, don't edit this file by hand.\n"
        "// </auto-generated>\n\n"
        "namespace Banccoon.App.Controls;\n\n"
        "// Glyphs in Resources/Fonts/Heroicons-Outline.ttf (Heroicons 2.2.0, outline, MIT), one per\n"
        "// Heroicons name. Used from XAML as Icon=\"{x:Static controls:Heroicons.Plus}\" on an IconButton.\n"
        "public static class Heroicons\n"
        "{\n"
        "    public const string FontFamily = \"Heroicons\";\n\n"
        f"{constants}\n"
        "}\n",
        encoding="utf-8",
        newline="\r\n")
    print(f"{len(names)} icons -> {FONT_OUT.relative_to(ROOT)} and {CS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
