// <auto-generated>
// Generated by tools/icon-font/build_heroicons_font.py from tools/icon-font/icons.txt - edit
// those and rerun, don't edit this file by hand.
// </auto-generated>

namespace Banccoon.App.Controls;

// Glyphs in Resources/Fonts/Heroicons-Outline.ttf (Heroicons 2.2.0, outline, MIT), one per
// Heroicons name. Used from XAML as Icon="{x:Static controls:Heroicons.Plus}" on an IconButton.
public static class Heroicons
{
    public const string FontFamily = "Heroicons";

    public const string Plus = "\uE000";
    public const string Minus = "\uE001";
    public const string XMark = "\uE002";
    public const string Check = "\uE003";
    public const string CheckCircle = "\uE004";
    public const string Funnel = "\uE005";
    public const string ClipboardDocumentCheck = "\uE006";
    public const string ArrowDownTray = "\uE007";
    public const string ArrowUpTray = "\uE008";
    public const string PencilSquare = "\uE009";
    public const string Trash = "\uE00A";
    public const string ArchiveBox = "\uE00B";
    public const string ArrowUturnLeft = "\uE00C";
    public const string ArrowUturnRight = "\uE00D";
    public const string Star = "\uE00E";
    public const string CreditCard = "\uE00F";
    public const string ListBullet = "\uE010";
    public const string Eye = "\uE011";
    public const string EyeSlash = "\uE012";
    public const string ArrowUp = "\uE013";
    public const string ArrowDown = "\uE014";
    public const string ArrowLeft = "\uE015";
    public const string ArrowRight = "\uE016";
    public const string ChevronLeft = "\uE017";
    public const string ChevronRight = "\uE018";
    public const string ChevronUp = "\uE019";
    public const string ChevronDown = "\uE01A";
    public const string Clock = "\uE01B";
    public const string Forward = "\uE01C";
    public const string Link = "\uE01D";
    public const string ArrowPath = "\uE01E";
    public const string ArrowPathRoundedSquare = "\uE01F";
    public const string LockClosed = "\uE020";
    public const string LockOpen = "\uE021";
    public const string DocumentText = "\uE022";
    public const string FolderOpen = "\uE023";
    public const string Tag = "\uE024";
    public const string DocumentDuplicate = "\uE025";
    public const string ArrowUpRight = "\uE026";
    public const string ArrowDownLeft = "\uE027";
    public const string ArrowsRightLeft = "\uE028";
    public const string Scale = "\uE029";
    public const string Banknotes = "\uE02A";
    public const string CalendarDays = "\uE02B";
    public const string Squares2x2 = "\uE02C";
    public const string NoSymbol = "\uE02D";
    public const string ArrowTopRightOnSquare = "\uE02E";
    public const string PlusCircle = "\uE02F";
    public const string MinusCircle = "\uE030";
    public const string MagnifyingGlass = "\uE031";
    public const string CheckBadge = "\uE032";
}
